server:
  port: 8083

spring:
  application:
    name: theater-service

  datasource:
    url: jdbc:postgresql://localhost:5432/theaterdb
    username: postgres
    password: 7860

  jpa:
    hibernate:
      ddl-auto: update
